#!/usr/bin/env bash
set -euo pipefail

list=" Lock\n Suspend\n Log Out\n Reboot\n Shutdown"

case $(echo -e "$list" | fzf --no-input) in
  *"Lock")
    systemd-run --user swaylock
    ;;
  *"Suspend")
    systemctl suspend
    ;;
  *"Log Out")
    niri msg action quit
    ;;
  *"Reboot")
    systemctl reboot
    ;;
  *"Shutdown")
    systemctl poweroff
    ;;
esac
