#!/usr/bin/env bash
set -euo pipefail

list=" Lock\n Suspend\n Log Out\n Reboot\n Shutdown"

if [ "$#" -eq 0 ]; then
    echo -e "$list"
    exit 0
fi

case "$1" in
*"Lock")
    swaylock -f
    ;;
*"Suspend")
    systemctl suspend
    ;;
*"Log Out")
    niri msg action quit
    ;;
*"Reboot")
    systemctl reboot
    ;;
*"Shutdown")
    systemctl poweroff
    ;;
esac
